services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql-data-1
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql-data-1:/var/lib/mysql
    networks:
      - twotierr
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  flask-app:
    image: hamzadevops01/two-tier-flask-app:latest
    container_name: flask-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: mysql-data-1
    depends_on:
      - mysql
    networks:
      - twotierr
    ports:
      - "5000:5000"
    restart: always

volumes:
  mysql-data-1:

networks:
  twotierr:
